name: CI on Master Branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1' # Change this to your desired Node.js version

      - name: Install PM2
        run: npm install pm2 -g

      - name: Check Node.js version
        run: node -v

      - name: Deploy with PM2
        run: pm2 deploy ecosystem.config.js production --force